repos:
  # Python linters and formatters
  - repo: https://github.com/pre-commit/mirrors-black
    rev: v23.9.1  # Use the latest version of Black
    hooks:
      - id: black
        args: ["--line-length", "88"]
        files: \.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: \.py$

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "88"]
        files: \.py$

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint

  # JavaScript/TypeScript/Svelte linters and formatters
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.50.0  # Use the latest ESLint version
    hooks:
      - id: eslint
        args: ["--ext", ".js,.svelte"]
        additional_dependencies: ["eslint-plugin-svelte@3.2.0"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0  # Use the latest Prettier version
    hooks:
      - id: prettier
        args: ["--write", "--plugin-search-dir=./frontend"]
        files: \.(js|svelte|css|json|yaml|yml|md)$
  
  # Tailwind CSS linting
  - repo: https://github.com/whiteinge/tailwindcss-pre-commit
    rev: v1.0.0
    hooks:
      - id: tailwindcss

  # General formatting checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
